name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        id-token: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install ko
        uses: ko-build/setup-ko@v0.7
        env:
            KO_DOCKER_REPO: us-central1-docker.pkg.dev/minder-zoo/spdx-detector

      - uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: projects/2476835098/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions
            project_id: minder-zoo

      # Build and push the application
      - name: Build application
        id: build
        run: echo "::set-output name=image::$(ko build)"

      # Publish the container to Google Artifact Registry
      - name: Push to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: "${{ steps.build.outputs.image}}"
          service: spdx-detector
          region: us-central1