name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install ko
        uses: ko-build/setup-ko@v0.7
        env:
            KO_DOCKER_REPO: us-central1-docker.pkg.dev/minder-zoo/spdx-detector

      - uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: projects//locations/global/workloadIdentityPools
            project_id: minder-zoo

      # Build and push the application
      - name: Build application
        run: ko build

      # Publish the container to Google Artifact Registry
      - name: Push to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: build.image
          service: spdx-detector
          region: us-central1